#! /bin/sh

# find IP
IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$1" --output text --query 'Reservations[].Instances[].[PublicIpAddress]')

# ask for location of pem key and then ssh the IP
case $IP in
    [0-9]*\.[0-9]*\.[0-9]*\.[0-9]* ) read -p "location of pem key file (eg. ~/.ssh/test_123.pem) >" key;set -o xtrace;ssh -i $key ec2-user@$IP;;
    * ) echo "Host​ not​ found";;
esac
