apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    app: url-shortener
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
      tier: api
  template:
    metadata:
      labels:
        app: url-shortener
        tier: api
    spec:
      containers:
      - name: url-shortener
        # replace with your pushed dockerhub image
        image: allthatjazzleo/fsdfqwefwxcsd:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: REDIS_ENDPOINT
          value: YOUR-AWS-REDIS-ENDPOINT
        - name: REDIS_PASSWORD
          value: YOUR-AWS-REDIS-TOKEN
        - name: REDIS_PORT
          value: YOUR-AWS-REDIS-PORT
        - name: DOMAIN
          value: YOUR-DOMAIN
        livenessProbe:
          httpGet:
            path: /ping
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ping
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

